export const GET_VAST_PENDING = 'GET_VAST_PENDING';
export const GET_VAST_SUCCESS = 'GET_VAST_SUCCESS';
export const GET_VAST_REJECTED = 'GET_VAST_REJECTED';
export const GET_VAST_TO_INITIAL = 'GET_VAST_TO_INITIAL';

export const GET_VAST_BY_ID_PENDING = 'GET_VAST_BY_ID_PENDING';
export const GET_VAST_BY_ID_SUCCESS = 'GET_VAST_BY_ID_SUCCESS';
export const GET_VAST_BY_ID_REJECTED = 'GET_VAST_BY_ID_REJECTED';
export const GET_VAST_BY_ID_TO_INITIAL = 'GET_VAST_BY_ID_TO_INITIAL';

export const CREATE_VAST_PENDING = 'CREATE_VAST_PENDING';
export const CREATE_VAST_SUCCESS = 'CREATE_VAST_SUCCESS';
export const CREATE_VAST_REJECTED = 'CREATE_VAST_REJECTED';
export const CREATE_VAST_TO_INITIAL = 'CREATE_VAST_TO_INITIAL';